// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR1568-gXLXMW6l9V52aH0ERgR0vzxvIU',
    appId: '1:1030581477394:android:2a826dddee323009bc38cb',
    messagingSenderId: '1030581477394',
    projectId: 'recycleconsumer-52f39',
    storageBucket: 'recycleconsumer-52f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkEIw5L5ZfSQLvn4JmS4dWrnlkJOBPiM',
    appId: '1:1030581477394:ios:6bdc37ce71d0a9f3bc38cb',
    messagingSenderId: '1030581477394',
    projectId: 'recycleconsumer-52f39',
    storageBucket: 'recycleconsumer-52f39.firebasestorage.app',
    iosBundleId: 'com.example.recycleBazaarConsumer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN4OdQmerlWymLBNdrFfiozxfC5KBm3vM',
    appId: '1:1030581477394:web:cabf65b73c3c8ef9bc38cb',
    messagingSenderId: '1030581477394',
    projectId: 'recycleconsumer-52f39',
    authDomain: 'recycleconsumer-52f39.firebaseapp.com',
    storageBucket: 'recycleconsumer-52f39.firebasestorage.app',
  );

}